### ISSUE TITLE
having issues running macro control

### ISSUE THREAD

**Issue by arcticzay** [Awashcard0/Natro-macro-control#4]
whenever i run startup.bat it gives me this
and i dont know how to fix it
![image](https://user-images.githubusercontent.com/65076423/215293159-61f2ca0a-35b9-4cf3-a0f7-cabe3b231bea.png)

**Comment by Bocon778** [comment]
You must enable intents for the bot. 
![image](https://user-images.githubusercontent.com/71742654/215300513-e81ee36c-84ed-4aad-92b8-a21cebccd8cd.png)

**Comment by Awashcard0** [comment]
in the Discord developer portal select bot then turn on all of the intents
